baseURL = 'https://thisisavs.github.io/'
languageCode = 'en-us'
title = 'A V S Sai Babu'
theme = 'hextra'

[params]
  description = "Personal website - TIL, projects, and thoughts"

  [params.blog.list]
    displayTags = true

  [params.toc]
    displayTags = true

  [params.navbar]
    displayTitle = true
    displayLogo = true
    [params.navbar.logo]
      path = "owl_logo.png"
      dark = "owl_logo_dark.png"
      width = 28
      height = 28

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 2
  [[menu.main]]
    name = "Now"
    pageRef = "/now"
    weight = 3
  [[menu.main]]
    name = "TIL"
    pageRef = "/til"
    weight = 4
  [[menu.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 5
  [[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 6

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
